name: "⚙️ CI Feature Branch"

on:
  push:
    branches:
      - feature**
      - '[0-9].[0-9].x'
      - 'v[0-9].[0-9].[0-9]'
      - 'v[0-9].[0-9].x'
      - docs**

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  ci-terraform:
    name: 🛠️ ci-terraform
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      - name: ⛏️ Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: ▶️ Terraform Init
        run: terraform init
        working-directory: infra/aws/get-active-tickers

      - name: ⏏️ Terraform Validate
        run: terraform validate
        working-directory: infra/aws/get-active-tickers

  open-pr-to-main:
    name: 🔓 open-pr-to-main
    runs-on: ubuntu-latest
    needs:
      - ci-terraform

    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      - name: 🔓 PR to main
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          title: "pr(main): ${{ github.ref }} -> main"
          body-path: ".github/pull_request_template.md"
          labels: "github-bot 🤖"
          commit-message: "bot: abertura automática de PR para branch main"
          
